spring:
  application:
    name: nameClassifier
  datasource:
    url: jdbc:postgresql://ep-mute-poetry-amyvhz5r-pooler.c-5.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_8JgqyVvpm6wl
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000